@extends('layouts.erp')

@section('title', 'Financial Reports')
@section('breadcrumb', 'Accounting / Financial Reports')

@section('content')
  <div class="page-header">
    <div>
      <div class="page-title">Financial Reports</div>
      <div class="page-subtitle">P&L, Balance Sheet and Cash Flow statements</div>
    </div>
    <div class="d-flex gap-2">
      <button class="btn-erp btn-outline btn-export"><i class="bi bi-download"></i> Export</button>
      <button class="btn-erp btn-primary" data-bs-toggle="modal" data-bs-target="#modalFinReport"><i
          class="bi bi-plus-lg"></i> Generate Report</button>
    </div>
  </div>

  <div class="erp-card">
    <div class="table-toolbar">
      <div class="search-input">
        <span class="si"><i class="bi bi-search"></i></span>
        <input type="text" class="tbl-search" data-table="#tbl-main" placeholder="Search financial reports…" />
      </div>
      <select class="erp-form-control" style="width:140px">
        <option>All Status</option>
        <option>P&L</option>
        <option>Balance Sheet</option>
        <option>Cash Flow</option>
      </select>
    </div>
    <div class="erp-table-wrap">
      <table class="erp-table" id="tbl-main">
        <thead>
          <tr>
            <th>Report Name</th>
            <th>Type</th>
            <th>Period</th>
            <th>Generated On</th>
            <th>Generated By</th>
            <th>Format</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          @foreach ($data as $report)
            <tr>
              <td>{{ $report->type ?? 'N/A' }} {{ $report->period ?? '' }}</td>
              <td>{{ $report->type ?? 'N/A' }}</td>
              <td>{{ $report->period ?? 'N/A' }}</td>
              <td>{{ $report->created_at ? \Carbon\Carbon::parse($report->created_at)->format('Y-m-d') : 'N/A' }}</td>
              <td>—</td>
              <td>{{ $report->format ?? 'PDF' }}</td>
              <td>
                <div class="d-flex gap-1"><button class="btn-erp btn-success btn-xs btn-icon btn-export"
                    title="Download"><i class="bi bi-download"></i></button><button
                    class="btn-erp btn-outline btn-xs btn-icon" data-bs-toggle="modal" data-bs-target="#modalFinReport"
                    title="Edit"><i class="bi bi-pencil"></i></button><button class="btn-erp btn-danger btn-xs btn-icon"
                    data-bs-toggle="modal" data-bs-target="#modalDelete" data-delete-label="Generate Report"
                    title="Delete"><i class="bi bi-trash"></i></button></div>
              </td>
            </tr>
          @endforeach
        </tbody>
      </table>
    </div>
    <div class="d-flex justify-content-between align-items-center mt-5">
      <div>
        Showing {{ $data->firstItem() }} to {{ $data->lastItem() }} of {{ $data->total() }}
      </div>
      <div>
        {{ $data->links('pagination::bootstrap-5') }}
      </div>
    </div>
  </div>

  <div class="modal fade" id="modalFinReport" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog  modal-dialog-centered modal-dialog-scrollable">
      <div class="modal-content"
        style="background:var(--bg-card);border:1px solid var(--border-active);border-radius:var(--radius)">
        <div class="modal-header" style="border-color:var(--border)">
          <h5 class="modal-title" style="color:var(--text-primary);font-weight:600">Generate Report</h5>
          <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
        </div>
        <div class="modal-body">
          <div class="row g-3">
            <div class="col-md-6"><label class="erp-form-label">Report Type</label><select class="erp-form-control">
                <option>Profit & Loss</option>
                <option>Balance Sheet</option>
                <option>Cash Flow</option>
                <option>Trial Balance</option>
              </select></div>
            <div class="col-md-6"><label class="erp-form-label">Period</label><select class="erp-form-control">
                <option>This Month</option>
                <option>Last Month</option>
                <option>This Quarter</option>
                <option>Custom</option>
              </select></div>
            <div class="col-md-6"><label class="erp-form-label">From Date</label><input class="erp-form-control"
                type="date" placeholder="" /></div>
            <div class="col-md-6"><label class="erp-form-label">To Date</label><input class="erp-form-control"
                type="date" placeholder="" /></div>
            <div class="col-md-4"><label class="erp-form-label">Format</label><select class="erp-form-control">
                <option>PDF</option>
                <option>Excel</option>
              </select></div>
          </div>
        </div>
        <div class="modal-footer" style="border-color:var(--border)">
          <button type="button" class="btn-erp btn-outline" data-bs-dismiss="modal">Cancel</button>
          <button type="button" class="btn-erp btn-primary btn-modal-save">
            <i class="bi bi-check2"></i> Generate
          </button>
        </div>
      </div>
    </div>
  </div>
  <!-- Delete Confirm Modal -->
  <div class="modal fade" id="modalDelete" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" style="max-width:400px">
      <div class="modal-content"
        style="background:var(--bg-card);border:1px solid var(--border-active);border-radius:var(--radius)">
        <div class="modal-header" style="border-color:var(--border)">
          <h5 class="modal-title" style="color:var(--accent-3)"><i class="bi bi-exclamation-triangle me-2"></i>Confirm
            Delete</h5>
          <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
        </div>
        <div class="modal-body">
          <p style="color:var(--text-secondary);font-size:14px">
            Are you sure you want to delete this
            <strong id="delete-target" style="color:var(--text-primary)">record</strong>?
            This action cannot be undone.
          </p>
        </div>
        <div class="modal-footer" style="border-color:var(--border)">
          <button type="button" class="btn-erp btn-outline" data-bs-dismiss="modal">Cancel</button>
          <button type="button" class="btn-erp btn-danger" id="btn-confirm-delete">
            <i class="bi bi-trash"></i> Delete
          </button>
        </div>
      </div>
    </div>
  </div>
@endsection
